---@alias color string

---@class oneiroi.palette
---@field fg color ---basic
---@field com color
---@field red color
---@field ora color
---@field yel color
---@field gre color
---@field aqu color
---@field blu color
---@field pur color
---@field sel color
---@field cur color
---@field bg color
---@field fg_s color
---@field com_s color
---@field red_s color
---@field ora_s color
---@field yel_s color
---@field gre_s color
---@field aqu_s color
---@field blu_s color
---@field pur_s color
---@field sel_s color
---@field cur_s color
---@field bg_s color
---@field bg2 color
---@field bg3 color
---@field war color ---info
---@field war_s color
---@field suc color
---@field suc_s color
---@field err color
---@field err_s color
---@field inf color;
---@field inf_s color;
---@field primary color ---addition
---@field secondary color
---@field tertiary color
---@field quaternary color
---@field quinary color
---@field senary color
---@field primary_s color ---addition
---@field secondary_s color
---@field tertiary_s color
---@field quaternary_s color
---@field quinary_s color
---@field senary_s color
---@field none color
---@field cursor color
---@field border color
---@field muted color
---@field muted_s color
---@field diagInfo color
---@field diagHint color
---@field diagWarning color
---@field diagSuccess color
---@field diagError color
---@field diffAdd color
---@field diffChange color
---@field diffDelete color
---@field diffText color
